#!/usr/bin/env zsh

DavmaildPattern="zsh.+\/davmaild"
KhalPattern="python.+\/khal interactive"

CalendarPath="$XDG_DATA_HOME/khal/calendars/uu/calendar"

davmaild_is_running(){
    pgrep -f "$DavmaildPattern" &> /dev/null
}

vdirsyncer_is_running() {
    pgrep -x "vdirsyncer" &> /dev/null
}

wait_for_vdirsyncer() {
    local index=0
    while vdirsyncer_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 180 ]]; then
            kill $(pgrep -x vdirsyncer) &> /dev/null
        fi
    done
}

if ! davmaild_is_running; then
    davmaild &> /dev/null &
    sleep 1
fi

files_in_cal_0=$(ls $CalendarPath)

wait_for_vdirsyncer
vdirsyncer sync &>/dev/null
