#!/usr/bin/env zsh

Pattern="zsh /home/jkorbmacher/.local/bin/csyncd"

RunningInstances=($(pgrep -f -c "$Pattern"))

if [[ ${#RunningInstances} -gt 1 ]]; then
    echo "Already running!"
    exit 0
fi

DavmaildPattern="zsh $XDG_CONFIG_HOME/davmail/scripts/davmaild"
KhalPattern="python.+\/khal interactive"

CalendarPath="$XDG_DATA_HOME/khal/calendars/uu/calendar"

davmaild_is_running(){
    pgrep -f "$DavmaildPattern" &> /dev/null
}

khal_is_running() {
    pgrep -f "$KhalPattern" &> /dev/null
}

vdirsyncer_is_running() {
    pgrep -x "vdirsyncer" &> /dev/null
}

wait_for_vdirsyncer() {
    local index=0
    while vdirsyncer_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 180 ]]; then
            kill $(pgrep -x vdirsyncer) &> /dev/null
        fi
    done
}

if ! davmaild_is_running; then
    davmaild &> /dev/null &
    sleep 1
fi

files_in_cal_0=$(ls $CalendarPath)

while true; do
    if khal_is_running; then
        files_in_cal_1=$(ls $CalendarPath)
        diff="$(echo ${files_in_cal_0[@]} ${files_in_cal_1[@]} | tr ' ' '\n' | sort | uniq -u)"
        if [[ -n $diff ]]; then
            wait_for_vdirsyncer
            vdirsyncer sync &>/dev/null
            files_in_cal_0=(${files_in_cal_1[@]})
        fi
    else
        wait_for_vdirsyncer
        vdirsyncer sync &>/dev/null
        break
    fi
    sleep 120
done
