#!/usr/bin/env zsh

Pattern="zsh $XDG_CONFIG_HOME/neomutt/scripts/msyncd"

RunningInstances=($(pgrep -f "$Pattern"))

if [[ ${#RunningInstances} -gt 1 ]]; then
    echo "Already running!"
    exit 0
fi

DavmaildPattern="zsh $XDG_CONFIG_HOME/davmail/scripts/davmaild"

davmaild_is_running(){
    pgrep -f "$DavmaildPattern" &> /dev/null
}

neomutt_is_running() {
    pgrep -x neomutt &> /dev/null
}

mbsync_is_running() {
    pgrep -x mbsync &> /dev/null
}

mu_is_running() {
    pgrep -x mu &> /dev/null
}

wait_for_mbsync() {
    local index=0
    while mbsync_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 180 ]]; then
            kill $(pgrep -x mbsync) &> /dev/null
        fi
    done
}

wait_for_mu() {
    local index=0
    while mu_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 120 ]]; then
            kill $(pgrep -x mu) &> /dev/null
        fi
    done
}

if ! davmaild_is_running; then
    echo "Starting daemon" >> ./log.txt
    davmaild &>/dev/null &
    sleep 1
fi

wait_for_mbsync

while true; do
    wait_for_mbsync
    if neomutt_is_running; then
        mbsync -qq uu:INBOX
    else
        mbsync -qq uu
        break
    fi
    wait_for_mu
    mu index -qq
    sleep 120
done
