#!/usr/bin/env zsh

DavmaildPattern="zsh $XDG_CONFIG_HOME/davmail/scripts/davmaild"

wait_for_mbsync() {
    local index=0
    while mbsync_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 180 ]]; then
            kill $(pgrep -x mbsync) &> /dev/null
        fi
    done
}

wait_for_mu() {
    local index=0
    while mu_is_running; do
        sleep 1
        ((index+=1))
        if [[ $index = 120 ]]; then
            kill $(pgrep -x mu) &> /dev/null
        fi
    done
}

mbsync_is_running() {
    pgrep -x mbsync &> /dev/null
}

mu_is_running() {
    pgrep -x mu &> /dev/null
}

davmaild_is_running(){
    pgrep -f "$DavmaildPattern" &> /dev/null
}

if ! davmaild_is_running; then
    davmaild &>/dev/null &
    sleep 1
fi

wait_for_mbsync

if [[ $1 == "-f" ]]; then
    mbsync -qq uu
else
    mbsync -qq uu:INBOX
fi
wait_for_mu
mu index -qq
