#!/bin/zsh

while :; do case $1 in
	--getsavefilename) file="$2" break ;;
	--version)
		printf ""
		exit
		;;
	--*) shift ;;
	*) break ;;
	esac done

file="${file##/*/}"

alacritty -T popup -e zsh -c "nnn -J -p - '$file' | awk '{ print system(\"[ -d '\''\"\$0\"'\'' ]\") ? \$0 : \$0\"/$file\" }' > /proc/$$/fd/1"
